language: erlang
otp_release:
   - R16B
   - R15B02
   - R15B01
   - R15B
   - R14B04
   - R14B03
   - R14B02
services: postgresql
before_script:
  - psql -c 'CREATE ROLE test LOGIN; ALTER USER test WITH SUPERUSER; CREATE DATABASE test WITH OWNER=test;' -U postgres
